config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :state_machines do 
    resources :state_machine_nodes do 
      member do 
        get 'generate_nodes'
        post 'export'
        post 'node_import'
        post 'generate_user_journey'
      end
    end
  end
  root 'users#index'

  post 'products/state_machine_journey' => 'state_machine_nodes#state_machine_journey', as: :state_machine_journey

end

app/models/state_machine_node.rb
class StateMachineNode < ActiveRecord::Base
  belongs_to :state_machine
  require 'csv'    
  def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv.add_row column_names
	    all.each do |foo|
	      values = foo.attributes.values
	      csv.add_row values
	    end
	  end
	end

	def self.import(file,state_machine_id)
		CSV.foreach(file, headers: true) do |row|
		  state_machine = StateMachineNode.new
		  state_machine.state_node_id = row.values_at[0]
		  state_machine.node_title = row.values_at[1]
		  state_machine.state_machine_id = state_machine_id
		  state_machine.parent_node_id << row.values_at[2]
		  state_machine.is_condition = row.values_at[3]
		  self.check_valid(state_machine)
		end
	end

	def self.check_valid(state_machine)
		init_node = StateMachineNode.find_by(state_machine_id: state_machine.state_machine_id,state_node_id: state_machine.state_node_id)
		if init_node.nil?
		  state_machine.save!
		end  
	end
end

app/controllers/state_machine_nodes_controller.rb
class StateMachineNodesController < ApplicationController
	include NodeSearch
	protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

	def index
	  @state_machine = StateMachine.find_by(id: params['state_machine_id'])	
	  respond_to do |format|
	    format.html
	    format.csv do
	      headers['Content-Disposition'] = "attachment; filename=\"StateMachineNodeList\""
	      headers['Content-Type'] ||= 'text/csv'
	    end
	  end
	end

	def generate_nodes
		@state_machine_nodes = StateMachineNode.where(state_machine_id: params[:id].to_i)
	end

	def export
		if params[:file].nil?
			redirect_to :back, notice: 'Please upload csv file.'
		else	
	    StateMachineNode.import(params[:file].path,params[:state_machine_id])	
	    redirect_to :back, notice: 'Csv file uploaded sucessfully.'
	  end  
	end

	def node_import
    if params[:file].nil?
    	redirect_to :back, notice: 'Please upload csv file.'
		else	
	    StateMachineNodeResource.node_import(params[:file].path,params[:state_machine_id])	
	    redirect_to '/state_machines', notice: 'Csv file uploaded sucessfully.'
	  end
	end

	def show
		@state_machine_node = StateMachineNode.find_by(params[:node_id])
	end

  def destroy
  	@state_machine_node = StateMachineNode.find_by(id: params[:id])
    @state_machine_node.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'State machine node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check
    @graph = Hash.new { |hash, key| hash[key] = [] }
  end

  def addEdge(a, b)
    @graph[a] << b
    @graph[b] << a
  end


  def searchPath(a, b, result,lr)
    result = result+[a]
    lr << result if a == b
    @graph[a].each do |v|
         searchPath(v, b, result,lr) if ! result.include?(v)
    end
  end
	
	def generate_user_journey
		unless (params[:pick_up_node] || params[:exit_node]).blank?
			@state_machine_nodes = StateMachineNodeResource.where(state_machine_id: params['state_machine_id']).pluck(:parent_node_id,:child_node_id)
			node_stack = check
			@state_machine_nodes.each do |node_row| 
        addEdge(node_row[0],node_row[1])  
			end	
		  searchPath(params[:pick_up_node],params[:exit_node], [],a=[])
		  jing = []
			a.each do |qax|
			  wssd = []
			  qax.each_cons(2) {|gtd| wssd << gtd}
		    ting = []
		    wssd.each do |rswe|
		      if @state_machine_nodes.include? rswe
		        ting << 'true'
		      else 
		        ting << 'false'  
		      end
		    end
		    ysd = ting.uniq
		    if ((ysd.count == 1) && (ysd.include? 'true'))
		      jing << qax
		    end
			end
			@record = jing
      respond_to do |format|
		    format.js
		  end
		end 
	end

	def send_min_length(record,rl)
		min_path_size = rl.min
    record_index = rl.each_index.select{|i| rl[i] != min_path_size}
    return record.delete_if.with_index { |_, index| record_index.include? index }
	end
end

app/helpers/state_machine_nodes_helper.rb
module StateMachineNodesHelper
	def record_title(record)
		@user_journeys = []
		record.each do |journey|
			user_journey = []
			node_ids = journey
      node_ids.each do |node_id| 
	      user_journey << StateMachineNode.find_by(state_machine_id: params[:id],state_node_id: node_id.strip).node_title
      end
      @user_journeys <<  user_journey
		end
		return @user_journeys.uniq
	end

	def record_count(record)
		record_title(record).count
	end
end

app/views/state_machine_nodes/_journey_form.html.erb
<p>There are <%= @record.count %> User Journey(s).</p> </br>
<% a = record_title(record) %>
<div class="container">
<% ind = 1 %>
<% a.each do |re| %>
  <p>UJ <%= ind %> : <%= re.join('-->')%>.</p>
  <br>
  <br>
  <% ind += 1 %>
<% end %>
</div>

app/views/state_machine_nodes/generate_nodes.html.erb
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
<div class="col-md-10 col-md-offset-1">
  <div class="panel panel-default panel-table">
    <div class="panel-heading">
      <div class="row">
        <div class="col col-xs-6">
          <h3 class="panel-title">Listing State Machine Nodes</h3>
          <p id="notice"><%= notice %>
        </div>
        <div class="col col-xs-6 text-right">
          <%= link_to 'BACK', state_machines_path ,class: "btn btn-sm btn-primary btn-create"%>
          <%= link_to 'SAMPLE CSV', state_machine_state_machine_nodes_path(format: :csv),class: "btn btn-sm btn-primary btn-create" %>
        </div>
        <div>
          <%= form_tag export_state_machine_state_machine_node_path(state_machine_id: params[:state_machine_id], id: params[:id]), multipart: true do %>
            <%= file_field_tag :file %>
            <%= submit_tag "Import CSV" %>
          <% end %>
        </div>
         <div>
          <%= form_tag node_import_state_machine_state_machine_node_path(state_machine_id: params[:state_machine_id], id: params[:id]), multipart: true do %>
            <%= file_field_tag :file %>
            <%= submit_tag "Import Node CSV" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <% if @state_machine_nodes.blank? %>
        NO DATA AVAILABLE
      <% else %>
        <table class="table table-striped table-bordered table-list">
          <thead>
            <tr>
              <th class="sm-action"><em class="fa fa-cog"></em></th>
              <th class="hidden-xs">ID</th>
              <th>Name</th>
              <!-- <th>Parent IDS</th> -->
              <!-- <th>IS Condition</th> -->
            </tr> 
          </thead>
          <tbody>
            <% @state_machine_nodes.each_with_index do |node, index| %>        
              <tr>
                <td align="center">               
                  <%= link_to '<i class="fa fa-eye"></i> '.html_safe,state_machine_state_machine_node_path(state_machine_id: node.state_machine_id,id: node.id) ,class: "btn btn-default"%>
                  <%#= link_to '<i class="fa fa-pencil"></i> '.html_safe, edit_state_machine_path(state_machine) ,class: "btn btn-default"%>
                  <%= link_to '<i class="fa fa-trash"></i> '.html_safe, state_machine_state_machine_node_path(state_machine_id: node.state_machine_id ,id: node) , method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger"%>
                </td>
                <td class="hidden-xs"><%= node.state_node_id %></td>
                <td><%= node.node_title %></td>
                <!-- <td><%#= node.parent_node_id %></td> -->
                <!-- <td><%#= node.is_condition ? 'TRUE' : 'FALSE' %></td> -->
              </tr>
              <div class="modal fade" id="smModal" role="dialog">
                <div class="modal-dialog">  
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Modal Header</h4>
                    </div>
                    <div class="modal-body">
                      <p>Some text in the modal.</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                  
                </div>
              </div>
            <% end %>    
          </tbody>
        </table>
      <% end %>  
    </div>
    <!-- <div class="panel-footer">
      <div class="row">
        <div class="col col-xs-4">Page 1 of 5
        </div>
        <div class="col col-xs-8">
          <ul class="pagination hidden-xs pull-right">
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
          </ul>
          <ul class="pagination visible-xs pull-right">
              <li><a href="#">«</a></li>
              <li><a href="#">»</a></li>
          </ul>
        </div>
      </div>
    </div> -->
  </div>
</div>

app/views/state_machine_nodes/generate_user_journey.js.erb
<% if @record.blank? %>
  bootbox.alert('Please Enter valid node points');
<% else %>
  $('#node-nj').hide();
  $('#btn-nj').hide();
  $('#sh-btn-nj').show();
  $('#out_put_journey').html("<%= j render 'journey_form' , record: @record %>");
<% end %>

app/views/state_machine_nodes/index.csv.erb
<% headers = ['Node-ID', 'Node-Description','Node-Points','Is-condition'] %>
<%= CSV.generate_line headers %>

app/views/state_machine_nodes/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="panel panel-default panel-table">
    <div class="panel-heading">
      <div class="row">
        <div class="col col-xs-6">
          <h3 class="panel-title">Generate Usecase Journey</h3>
          <p id="notice"><%= notice %>
        </div>
        <div class="col col-xs-6 text-right">
          <%= link_to 'BACK', state_machines_path ,class: "btn btn-sm btn-primary btn-create" ,id: 'btn-nj'%>
          <button class="btn btn-primary pull-right" id="sh-btn-nj" style="display: none;" type="button" value="Back" onClick="window.location.reload()">Back</button>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <%= image_tag @state_machine.photo.url(:large) %>
    </div>
    <br>
    <div id='result-note' style="display:none;">
      <h1>Please Wait For Results</h1>
      </div>
    <div id='node-nj'>
  
      <div class="form-group">
        <label>Node Pick-up : <div class="ras-node">
        <%= select("node_title", "id", StateMachineNode.all.collect {|r| [ r.state_node_id+" - "+r.node_title, r.state_node_id ] }, { :include_blank => true },id: "InputNode") %>
        </div></label>
        
      </div>
      <div class="form-group">
        <label>Node Exit : <div class="ras-node">
        <%= select("node_title", "id", StateMachineNode.all.collect {|r| [ r.state_node_id+" - "+r.node_title, r.state_node_id ] }, { :include_blank => true },id: "ExitNode") %>
        </div></label>
      </div>
      <button type="submit" class="btn btn-primary" id="state_machine_journey">Generate User Journey</button>     
    </div>
    <br>
    <div id="out_put_journey">
    </div>
  </div>
  
</div>

<script type="text/javascript">
  $("#state_machine_journey").click(function() {
    $('#result-note').show().fadeOut(10000);
    var p_node = $('#InputNode').val();
    var e_node = $('#ExitNode').val();
    if(p_node == '' && e_node == ''){
      bootbox.alert('enter values in search nodes');
      return false;
    }else{
    $.ajax({
        url: "/state_machines/<%= @state_machine.id%>/state_machine_nodes/<%= @state_machine.id %>/generate_user_journey",
        type: "POST",
        data: {pick_up_node: $(InputNode).val(),exit_node: $(ExitNode).val() }
    }); 
    } 
  });
  $( "#InputNode, #ExitNode" ).select2({
    theme: "bootstrap"
  });
</script>

app/views/state_machine_nodes/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">State Machine Node </div>
  <p id="notice"><%= notice %></p>
  <div>
    <strong>Node Name:</strong>
    <%= @state_machine_node.node_title %>
  </div><br>
  <div>
    <strong>Node ID:</strong>
    <%= @state_machine_node.state_node_id %>
  </div><br>
  <div>
    <!-- <strong>Is Condition:</strong> -->
    <%#= @state_machine_node.is_condition ? 'TRUE' : 'FALSE' %>
  </div><br>
  <div>
    <!-- <strong>Parent Node Id:</strong> -->
    <%#= @state_machine_node.parent_node_id.compact.blank? ? 'NIL' : @state_machine_node.parent_node_id %>
  </div><br>
  <%= link_to 'Back', generate_nodes_state_machine_state_machine_node_path(state_machine_id: @state_machine_node.state_machine_id) ,class: "btn btn-default"%>
</div>