config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :state_machines do 
    resources :state_machine_nodes do 
      member do 
        get 'generate_nodes'
        post 'export'
        post 'node_import'
        post 'generate_user_journey'
      end
    end
  end
  root 'users#index'

  post 'products/state_machine_journey' => 'state_machine_nodes#state_machine_journey', as: :state_machine_journey

end

app/models/state_machine.rb
class StateMachine < ActiveRecord::Base
  has_attached_file :photo, :styles => { :small => "150x150>" ,:ultra_large => "2000x2000>", :original => "500x500>", :large => "800x800>" }
  do_not_validate_attachment_file_type :photo
  has_many :state_machine_nodes , :dependent => :destroy
  has_many :state_machine_resource_nodes 
end

app/controllers/state_machines_controller.rb
class StateMachinesController < ApplicationController
  before_action :set_state_machine, only: [:show, :edit, :update, :destroy]

  # GET /state_machines
  # GET /state_machines.json
  def index
    @state_machines = StateMachine.all
  end

  # GET /state_machines/1
  # GET /state_machines/1.json
  def show
  end

  # GET /state_machines/new
  def new
    @state_machine = StateMachine.new
  end

  # GET /state_machines/1/edit
  def edit
  end

  # POST /state_machines
  # POST /state_machines.json
  def create
    @state_machine = StateMachine.new(state_machine_params)

    respond_to do |format|
      if @state_machine.save
        format.html { redirect_to @state_machine, notice: 'State machine was successfully created.' }
        format.json { render :show, status: :created, location: @state_machine }
      else
        format.html { render :new }
        format.json { render json: @state_machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /state_machines/1
  # PATCH/PUT /state_machines/1.json
  def update
    respond_to do |format|
      if @state_machine.update(state_machine_params)
        format.html { redirect_to @state_machine, notice: 'State machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @state_machine }
      else
        format.html { render :edit }
        format.json { render json: @state_machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /state_machines/1
  # DELETE /state_machines/1.json
  def destroy
    @state_machine.destroy
    respond_to do |format|
      format.html { redirect_to state_machines_url, notice: 'State machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state_machine
      @state_machine = StateMachine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_machine_params
      params.require(:state_machine).permit(:name, :node,:photo)
    end
end

app/helpers/state_machines_helper.rb
module StateMachinesHelper
end

app/views/state_machines/_form.html.erb
<%= form_for(@state_machine) do |f| %>
  <% if @state_machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state_machine.errors.count, "error") %> prohibited this state_machine from being saved:</h2>

      <ul>
      <% @state_machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :File %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/state_machines/edit.html.erb
<div class="panel panel-default">
  <div class="panel-body"><h1>Editing State Machine</h1></div>
  <%= render 'form' %>
  <%= link_to 'Show', @state_machine %> |
  <%= link_to 'Back', state_machines_path %>
</div>

app/views/state_machines/index.html.erb
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
<div class="col-md-10 col-md-offset-1">
  <div class="panel panel-default panel-table">
    <div class="panel-heading">
      <div class="row">
        <div class="col col-xs-6">
          <h3 class="panel-title">Listing State Machines</h3>
          <p id="notice"><%= notice %>
        </div>
        <div class="col col-xs-6 text-right">
          <%= link_to 'New State machine', new_state_machine_path ,class: "btn btn-sm btn-primary btn-create"%>
        </div>
      </div>
    </div>
    <div class="panel-body">
      <table class="table table-striped table-bordered table-list">
        <thead>
          <tr>
            <th class="sm-action"><em class="fa fa-cog"></em></th>
            <th class="hidden-xs">ID</th>
            <th>Name</th>
          </tr> 
        </thead>
        <tbody>
          <% @state_machines.each_with_index do |state_machine, index| %>        
            <tr>
              <td align="center">
                <%= link_to '<i class="fa fa-eye" data-toggle="tooltip" title="Show"></i> '.html_safe, state_machine ,class: "btn btn-default"%>
                <%= link_to '<i class="fa fa-pencil" data-toggle="tooltip" title="Edit!"></i> '.html_safe, edit_state_machine_path(state_machine) ,class: "btn btn-default"%>
                <%= link_to '<i class="fa fa-desktop" data-toggle="tooltip" title="User Journey"></i> '.html_safe, state_machine_state_machine_nodes_path(state_machine) ,class: "btn btn-default"%>
                <%= link_to '<i class="fa fa-cogs" data-toggle="tooltip" title="Upload CSV"></i> '.html_safe, generate_nodes_state_machine_state_machine_node_path(state_machine_id: state_machine, id: state_machine.id) ,class: "btn btn-default"%>
                <%= link_to '<i class="fa fa-trash" data-toggle="tooltip" title="Delete"></i> '.html_safe, state_machine , method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger"%>
              </td>
              <td class="hidden-xs"><%= index+1 %></td>
              <td><%= state_machine.name %></td>
            </tr>
          <% end %>  
        </tbody>
      </table>
    </div>
    <!-- <div class="panel-footer">
      <div class="row">
        <div class="col col-xs-4">Page 1 of 5
        </div>
        <div class="col col-xs-8">
          <ul class="pagination hidden-xs pull-right">
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
          </ul>
          <ul class="pagination visible-xs pull-right">
              <li><a href="#">«</a></li>
              <li><a href="#">»</a></li>
          </ul>
        </div>
      </div>
    </div> -->
  </div>
</div>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>

app/views/state_machines/new.html.erb
<div class="panel panel-default">
  <div class="panel-body"><h1>New State Machine</h1></div>
  <%= render 'form' %>
  <%= link_to 'Back', state_machines_path %>
</div>

app/views/state_machines/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="panel panel-default panel-table">
    <div class="panel-heading">
      <div class="row">
        <div class="col col-xs-6">
          <h3 class="panel-title">State Machine</h3>
          <p id="notice"><%= notice %>
        </div>
        <div class="col col-xs-6 text-right">
          <%= link_to 'BACK', state_machines_path ,class: "btn btn-sm btn-primary btn-create" ,id: 'btn-nj'%>

        </div>
      </div>
    </div>
    <div class="panel-body">
      <div>
        <strong>Name:</strong>
        <%= @state_machine.name %>
      </div><br>
      <div>  
        <strong>File:</strong>
        <%= image_tag @state_machine.photo.url(:ultra_large),style: 'width: 926px; height: 520px' %>
      </div> 
    </div>
    <br>
  </div>
</div>